version: "3"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
      - notification-service
      - auth-service

  user-service:
    build: ./user-service

  product-service:
    build: ./product-service
  
  order-service:
    build: ./order-service

  notification-service:
    build: ./notification-service
  
  auth-service:
    build: ./auth-service
    depends_on:
      - mysql
    environment:
      - APP_KEY=base64:ttRvj4zMUt5Gf764lufHqiorFpNlgJxbjNfEQeWq0Ow=
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - APP_URL=http://localhost:8000

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"